# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4c5bd5fd14221b5fc1c8db2e81490149ba6935a0cc78267a0e03a5f2952e54e89fc555234c4f137b705e8a54d9f35e650bec766276f2cb17a4c68c8464b9c5f

test:
  secret_key_base: 4b17c2a87ada51cc08f18828382b51023e8ecc9732fbbe4c48540527f7ab116b25f3e29818d5d11dc4077b7e2e2fd1e308d72c9a24d69455745dc7f79612d49f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
